name: master-actions
run-name: RELEASE
on:
  push:
    branches:
      - master

jobs:
  tag-release:
    runs-on: ubuntu-24.04
    steps:
      - name: Release
        uses: RedSockActions/release_tag@v1.1.6
        with:
          token: ${{ github.token }}